export const DEFAULT_SCALE = {
  name: 'A minor pentatonic',
  rootMidi: 45,
  intervals: [0, 3, 5, 7, 10],
  octaves: 4,
};

export const DEFAULT_LAYERS = [
  {
    name: 'Ink Bloom',
    layerType: 'shape',
    shapeType: 'polygon',
    numSides: 6,
    curviness: 0.82,
    wobble: 0.45,
    wobbleSpeed: 0.8,
    noiseAmount: 0.38,
    noiseScale: 1,
    opacity: 0.88,
    blendMode: 'screen',
    colors: ['#ffe08a', '#ff8c69', '#f84f73'],
    movementStyle: 'drift',
    movementSpeed: 1.1,
    movementAngle: 28,
    radiusFactor: 0.1,
    rotation: 0,
    xOffset: 0,
    yOffset: 0,
    freq1: 2,
    freq2: 3,
    freq3: 5,
    orbitRadiusX: 0.12,
    orbitRadiusY: 0.1,
    visible: true,
  },
  {
    name: 'Glass Orbit',
    layerType: 'shape',
    shapeType: 'polygon',
    numSides: 4,
    curviness: 0.18,
    wobble: 0.22,
    wobbleSpeed: 0.45,
    noiseAmount: 0.14,
    noiseScale: 0.8,
    opacity: 0.72,
    blendMode: 'overlay',
    colors: ['#7dd3fc', '#60a5fa', '#c084fc'],
    movementStyle: 'orbit',
    movementSpeed: 0.85,
    movementAngle: 315,
    radiusFactor: 0.085,
    rotation: 16,
    xOffset: 0,
    yOffset: 0,
    freq1: 2,
    freq2: 4,
    freq3: 6,
    orbitRadiusX: 0.18,
    orbitRadiusY: 0.14,
    visible: true,
  },
  {
    name: 'Deep Petal',
    layerType: 'shape',
    shapeType: 'polygon',
    numSides: 9,
    curviness: 0.94,
    wobble: 0.6,
    wobbleSpeed: 1.2,
    noiseAmount: 0.55,
    noiseScale: 1.15,
    opacity: 0.62,
    blendMode: 'lighten',
    colors: ['#4ade80', '#14b8a6', '#0f766e'],
    movementStyle: 'bounce',
    movementSpeed: 1.35,
    movementAngle: 132,
    radiusFactor: 0.12,
    rotation: -12,
    xOffset: 0,
    yOffset: 0,
    freq1: 3,
    freq2: 5,
    freq3: 7,
    orbitRadiusX: 0.1,
    orbitRadiusY: 0.08,
    visible: true,
  },
];

export function createDefaultScene() {
  return {
    name: 'Bloom Demo',
    backgroundColor: '#08121A',
    globalBlendMode: 'source-over',
    scale: DEFAULT_SCALE,
    layers: DEFAULT_LAYERS,
    sourceSummary: 'Bundled Bloom demo scene',
    exportMeta: null,
  };
}
